# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allegato',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField(max_length=10)),
                ('nome', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=8)),
                ('relURI', models.CharField(max_length=256)),
                ('dimensione', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'allegati',
            },
        ),
        migrations.CreateModel(
            name='PuntoODG',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('denominazione', models.CharField(max_length=512)),
                ('progressivo', models.IntegerField(default=1, help_text='Posizione in sequenza odg')),
                ('ordine', models.CharField(default='1', help_text='Indicazione punto PuntoODG: 1, 1a, 1b, 1b.2...', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'punti ODG',
            },
        ),
        migrations.CreateModel(
            name='Seduta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='Pre CIPE', help_text='Tipo di seduta, se CIPE o Pre CIPE', max_length=10, verbose_name='Tipo di seduta')),
                ('data', models.DateField(help_text='Data della seduta', max_length=10, verbose_name='Data seduta')),
                ('ufficiale', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'sedute',
            },
        ),
        migrations.AddField(
            model_name='puntoodg',
            name='seduta_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area_riservata.Seduta'),
        ),
        migrations.AddField(
            model_name='allegato',
            name='punto_odg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='area_riservata.PuntoODG'),
        ),
    ]
