# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allegato',
            old_name='punto_odg_id',
            new_name='punto_odg',
        ),
        migrations.RenameField(
            model_name='puntoodg',
            old_name='seduta_id',
            new_name='seduta',
        ),
    ]
