# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 08:25
from __future__ import unicode_literals

import area_riservata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0003_auto_20170408_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegato',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=area_riservata.models.relURI_path),
        ),
    ]
