# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-10 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0004_allegato_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='relURI',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
