# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-11 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0005_auto_20170410_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoodg',
            name='denominazione',
            field=models.TextField(max_length=512),
        ),
    ]
