# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0006_auto_20170411_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='seduta',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='puntoodg',
            name='denominazione',
            field=models.TextField(max_length=1024),
        ),
    ]
