# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0007_auto_20170412_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seduta',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
