# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0009_auto_20170414_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seduta',
            name='tipo',
            field=models.CharField(choices=[('precipe', 'Pre CIPE'), ('cipe', 'CIPE')], default='precipe', help_text='Tipo di seduta, se CIPE o Pre CIPE', max_length=10, verbose_name='Tipo di seduta'),
        ),
    ]
