# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0010_auto_20170418_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='seduta',
            name='id_seduta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seduta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='seduta',
            unique_together=set([('tipo', 'id_seduta')]),
        ),
    ]
