# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0011_auto_20170418_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='allegato',
            name='id_allegato',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
