# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0013_auto_20170426_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntoodg',
            name='id_punto_odg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
