# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0015_auto_20170426_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='relURI',
            field=models.CharField(max_length=255),
        ),
    ]
