# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0016_auto_20170426_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='nome',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='allegato',
            name='relURI',
            field=models.CharField(max_length=512),
        ),
    ]
