# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-22 11:35
from __future__ import unicode_literals

import area_riservata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area_riservata', '0017_auto_20180322_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allegato',
            name='file',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=area_riservata.models.relURI_path),
        ),
    ]
